[package]
name = "euler_fluid_sim"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
iced = {version = "0.10", features = ["canvas", "tokio"]}
itertools = "0.11.0"
tokio = "1.33.0"
rustc-hash = "1.0"